### ISSUE TITLE
it's a damn rickroll

### ISSUE THREAD

**Issue by mikeycl** [DerGoogler/powershell#1]
ha ha very funny been a long time since someone has managed that one with me

had to put this somewhere so feel free to close or remove just wanted to acknowledge it and inform you your plan succeeded at least once

Kudo's

**Comment by DerGoogler** [comment]
that is nice to hear xD

**Comment by webmaster-exit-1** [comment]
twice 
![giphy.gif](https://github.com/DerGoogler/powershell/assets/98633966/a132891d-f1a5-480a-887a-8d76c5490eb4)
