### ISSUE TITLE
It's a launcher and copied my image 

### ISSUE THREAD

**Issue by blank9485** [DerGoogler/powershell#5]
The launcher is called yantra launcher.
It's a CLI launcher for android where you customize it as you want.
The image is from my TikTok video
![Screenshot_20240801-133829](https://github.com/user-attachments/assets/ad273535-ee3f-46bb-8210-6eb239f4ccbd)

**Comment by DerGoogler** [comment]
So, what is exactly your request?

@blank9485

**Comment by blank9485** [comment]
That you didn't gave any credits to my image.

**Comment by blank9485** [comment]
At least make a screenshot by yourself instead of getting mine
